device_id = "f7a35dc0-37e4-4eea-94ec-adeaf8b4a340"
access_token = "578857e7-7ec7-4317-8ef6-e3608891b4a4"
cert_pem = ""
key_pem = ""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:8c63:65dd:9c49:3bbf:c0a7"
wg_private_key = "gNfCJLQ1FSlOqMglql0ROlM9mb7glJFx1OS8JCNkA0w="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "r8cK"
