device_id = "25796790-a343-4920-93f8-c8b4acc46362"
access_token = "1cfb535f-ab07-4bdf-990d-367716302db6"
cert_pem = """
-----BEGIN CERTIFICATE-----
MIHsMIGToAMCAQICAQAwCgYIKoZIzj0EAwIwADAeFw0yNjA3MjYxNjM5MTZaFw0y
NjA3MjcxNjM5MTZaMAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARu2KCMkMB8
4cMhH2ybXIstlJmOUiTJLF5s2b1l52dAx3DdwlVU1rIThZUSZ4VnKHYyV3g6UEv9
oAdlUVGWwjMKMAoGCCqGSM49BAMCA0gAMEUCIQDPiIzVs7VufM+2O7JyX1vvbQMM
LG/A0kgJrPWPCRXTrAIgEBwXmBnB37oRJ/uubhUwRvNlRISo6IRr8StttTXZpic=
-----END CERTIFICATE-----
"""
key_pem = """
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgQzc1nZXMXnCqb5pA
yrqMlb9ojVUzHeRu9kHkOOcp/pChRANCAARu2KCMkMB84cMhH2ybXIstlJmOUiTJ
LF5s2b1l52dAx3DdwlVU1rIThZUSZ4VnKHYyV3g6UEv9oAdlUVGWwjMK
-----END PRIVATE KEY-----
"""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:886e:ed38:7fa9:48d7:baea"
wg_private_key = "WJ4ssN+jB7z48FcS5MMmfGEP6vbiRbIOOCYTm60gcVc="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "3BjW"
